export const SET_MOUSE_POSITION = "SET_MOUSE_POSITION";
export const MOVING_ELEMENT = "MOVING_ELEMENT";
export const UPDATE_ELEMENTS = "UPDATE_ELEMENTS";
export const SET_SELECTED_ELEMENT_ID = "SET_SELECTED_ELEMENT_ID";
